name: GitHub Actions CI

#mainブランチにpushしたときに実行される
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: GitOps Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      #config/mainをチェックアウト
      - name: Checkout config
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.GIT_USERNAME }}/config
          token: ${{ secrets.CONFIG_PAT }}
      
      #gitの設定
      - name: git config
        run: |
          ls -la
          git config --global user.email "${{ secrets.MAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
      
            # values.yamlの更新、新規ブランチ作成、プッシュ、プルリクエスト
      
      #新しくブランチを作成してvalues.yamlを書き換えてPush
      - name: make new branch, update values.yaml
        run: |
          # 新規ブランチ作成
          git branch feature/${{ github.run_number }}
          git checkout feature/${{ github.run_number }}
          # values.yamlのタグ番号を更新
          sed -i 's/tag: [0-9]*/tag: ${{ github.run_number }}/g' gitops-helm/values.yaml

          #add, commit, push
          git add gitops-helm/values.yaml
          git commit -m "Update tag ${{ github.run_number }}"
          git push origin feature/${{ github.run_number }}
      
      #PR
      -name: pull request
        run: |
          gh pr create  --title "Update Tag ${{ github.run_number }}" --body "Please Merge !!"