name: GitHub Actions CI

#mainブランチにpushしたときに実行される
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: GitOps Workflow
    runs-on: ubuntu-latest
    steps:
      #code/mainをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3
      
      #config/mainをチェックアウト
      - name: Checkout code2
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.GIT_USERNAME }}/config
          token: ${{ secrets.CONFIG_PAT }}
      
      #test1
      - name: test1
        run: |
          ls -la
          cd gitops-helm
          git config --global user.email "${{ secrets.MAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
      
      #test2
      - name: test2
        run: |
          # 新規ブランチ作成
          git branch feature/${{ github.run_number }}
          git checkout feature/${{ github.run_number }}
          # values.yamlのタグ番号を更新
          sed -i 's/tag: [0-9]*/tag: ${{ github.run_number }}/g' values.yaml

      #test3
      - name: test3
        run: |
          #add, commit, push
          git add values.yaml
          git commit -m "Update tag ${{ github.run_number }}"
          git push origin feature/${{ github.run_number }}