name: GitHub Actions CI

#mainブランチにpushしたときに実行される
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: GitOps Workflow
    runs-on: ubuntu-latest
    steps:
      #code/mainをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3
      
      #test
      - name: test1
        run: |
          pwd
          ls -la
      
      #configリポジトリのmainブランチのチェックアウト
      - name: Checkout code2
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.GIT_USERNAME }}/config
          token: ${{ secrets.CONFIG_PAT }}
          path: ../../config
      
      #test
      - name: test2
        run: |
          pwd
          ls -la